### ISSUE TITLE
typo in usage example

### ISSUE THREAD

**Issue by johnjbarton** [joehewitt/transformjs#1]
Hi Joe, I guess the Usage example should be next() not next(node):

var ast = transformjs.transform('if (1) { a() } else { b() }', [
    function(node, next) {
        if (node.type == 'num') {
            return {type: 'num', value: 2};
        } else {
            return next(node);
-------------------------^
        }
    },
]);

**Comment by joehewitt** [comment]
Thanks, fixed!
